"""updated users table

Revision ID: 468596e9a4be
Revises: 8cf82cec8c5f
Create Date: 2025-04-16 04:48:59.223216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468596e9a4be'
down_revision: Union[str, None] = '8cf82cec8c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    userrole_enum = sa.Enum('USER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN', name='userrole')
    userstatus_enum = sa.Enum('PENDING', 'ACTIVE', 'BLOCKED', 'DISABLED', 'DELETED', name='userstatus')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    userstatus_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_status_id_fkey', 'users', type_='foreignkey')
    op.drop_index('ix_user_roles_id', table_name='user_roles')
    op.drop_index('ix_user_status_id', table_name='user_status')
    op.drop_column('users', 'status_id')
    op.drop_column('users', 'role_id')
    op.drop_table('user_roles')
    op.drop_table('user_status')
    op.add_column('users', sa.Column('role', userrole_enum, nullable=False))
    op.add_column('users', sa.Column('status', userstatus_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_status_id_fkey', 'users', 'user_status', ['status_id'], ['id'])
    op.create_foreign_key('users_role_id_fkey', 'users', 'user_roles', ['role_id'], ['id'])
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.create_table('user_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_status_pkey')
    )
    op.create_index('ix_user_status_id', 'user_status', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_roles_pkey')
    )
    op.create_index('ix_user_roles_id', 'user_roles', ['id'], unique=False)
    # ### end Alembic commands ###
