"""added employee profile picture

Revision ID: 83b95b998839
Revises: a3739eb39806
Create Date: 2025-05-25 23:57:42.073041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b95b998839'
down_revision: Union[str, None] = 'a3739eb39806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('profile_picture', sa.String(), nullable=True))
    op.drop_index('ix_employees_firstname', table_name='employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_employees_firstname', 'employees', ['firstname'], unique=True)
    op.drop_column('employees', 'profile_picture')
    # ### end Alembic commands ###
