"""added locations

Revision ID: c8462a82edb8
Revises: cc0d3f603f7f
Create Date: 2025-05-17 15:53:33.849923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8462a82edb8'
down_revision: Union[str, None] = 'cc0d3f603f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'city')
    op.add_column('locations', sa.Column('state', sa.String(), nullable=False))
    op.add_column('locations', sa.Column('city', sa.String(), nullable=False))
    op.add_column('locations', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('address_line2', sa.String(), nullable=True))
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('locations', 'address_line2')
    op.drop_column('locations', 'address_line1')
    op.drop_column('locations', 'postal_code')
    op.drop_column('locations', 'city')
    op.drop_column('locations', 'state')
    op.add_column('companies', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
