"""fixed employee status enum

Revision ID: f290007614c7
Revises: a3739eb39806
Create Date: 2025-05-22 16:49:30.853468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = 'f290007614c7'
down_revision: Union[str, None] = 'a3739eb39806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'status',
        existing_type=postgresql.ENUM('WORKING', 'RETIRED', name='employeestatus'),
        type_=sa.String(),
        nullable=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
